name: Deploy Flutter Web to Another Repo

on:
  push:
    branches:
      - main
      - master
      - development

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --output wwwroot/main_web

      - name: Deploy to output repo
        run: |
          cd wwwroot/main_web

          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/nazzz-infotech/web-output.git

          git checkout -b main
          git add .
          git commit -m "Deployed web build from main repo [skip ci]"
          git push -f origin main