name: Deploy Flutter Website

on:
  push:
    branches:
      - main
      - master
      - development

jobs:
  build_flutter_website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: stable

      - name: Disable animation
        run: flutter config --no-cli-animations

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --output wwwroot/main_web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: wwwroot   # ✅ Deploy whole wwwroot, including SEO + main_web/
          publish_branch: gh-pages